name: Publish NPM Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - run: npm install
      - run: npm install turbo --global
      - run: npm run build:package

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - name: Install turbo globally
        run: npm install turbo --global
      - name: Publish Stark dist folder
        run: npm run publish:package
        env:
          NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}
